In [1]:
import numpy as np

Numpy - Array Manipulation

In [2]:
arr=np.random.randint(1,10,(4,4))

In [3]:
arr

array([[1, 5, 3, 8],
       [7, 1, 8, 1],
       [8, 5, 5, 2],
       [5, 3, 1, 1]])

In [4]:
#lets try reshaping the matrix
arr.reshape(8,2)

array([[1, 5],
       [3, 8],
       [7, 1],
       [8, 1],
       [8, 5],
       [5, 2],
       [5, 3],
       [1, 1]])

In [5]:
#T means transpose, it is used for rotating array, that is row will become column and column will become row
arr.T

array([[1, 7, 8, 5],
       [5, 1, 5, 3],
       [3, 8, 5, 1],
       [8, 1, 2, 1]])

In [6]:
#to make a 1d array we use flatten function, in this case arr.flatten, this way all the array elements will be in 1d
arr.flatten()

array([1, 5, 3, 8, 7, 1, 8, 1, 8, 5, 5, 2, 5, 3, 1, 1])

In [7]:
#if we want to expand dimension that is expand from 2d to 3d or 4d we use np.expand_dims, while doing its important to mention
#the axis 
np.expand_dims(arr,axis=1)

array([[[1, 5, 3, 8]],

       [[7, 1, 8, 1]],

       [[8, 5, 5, 2]],

       [[5, 3, 1, 1]]])

In [8]:
np.expand_dims(arr,axis=2)

array([[[1],
        [5],
        [3],
        [8]],

       [[7],
        [1],
        [8],
        [1]],

       [[8],
        [5],
        [5],
        [2]],

       [[5],
        [3],
        [1],
        [1]]])

In [9]:
np.expand_dims(arr,axis=0)

array([[[1, 5, 3, 8],
        [7, 1, 8, 1],
        [8, 5, 5, 2],
        [5, 3, 1, 1]]])

In [10]:
#lets create a data set of 2d
data=np.array([[1],[2],[3]])

In [11]:
data

array([[1],
       [2],
       [3]])

In [12]:
#if we want to reduce dimension we use squeeze function
np.squeeze(data)

array([1, 2, 3])

In [13]:
#if we want the elements to be repeated in an array, while doing its important to mention how many time we want the elements to
#be repeated, in this case i have mentioned 2 as no of times i want the element to be repeated
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [14]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [15]:
#if we want to roll the data, we use np.roll, important to mention the step size, in this case its 1
np.roll(data,1)
#to roll means it roll the data, here step size is 1 means, initially we elements 1 2 3, to roll by 1 means 1 will 
#move by 1 step to 2s position, 2 will move by 1 step to 3s position, 3 will move by 1 step to 1s position 

array([[3],
       [1],
       [2]])

In [16]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [17]:
#if we want to the elements to be places in diagonal manner,we use np.diag
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Numpy - Binary Operations

In [20]:
#lets create random numbers
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [21]:
arr1

array([[6, 2, 1, 5],
       [3, 3, 7, 5],
       [7, 8, 4, 7]])

In [22]:
arr2

array([[1, 6, 2, 7],
       [6, 7, 7, 1],
       [3, 7, 7, 7]])

#we can perform binary operations in numpy like add,subtract,multiple,divide,negate, all these operation are done index wise
arr1+arr2
#we can notice it will perform index wise additiion

In [25]:
arr1*arr2
#this is also index wise multiplication

array([[ 6, 12,  2, 35],
       [18, 21, 49,  5],
       [21, 56, 28, 49]])

In [26]:
arr1/arr2

array([[6.        , 0.33333333, 0.5       , 0.71428571],
       [0.5       , 0.42857143, 1.        , 5.        ],
       [2.33333333, 1.14285714, 0.57142857, 1.        ]])

In [27]:
arr1-arr2

array([[ 5, -4, -1, -2],
       [-3, -4,  0,  4],
       [ 4,  1, -3,  0]])

In [28]:
#** means power of
arr1**arr2

array([[      6,      64,       1,   78125],
       [    729,    2187,  823543,       5],
       [    343, 2097152,   16384,  823543]])

In [29]:
~arr1

array([[-7, -3, -2, -6],
       [-4, -4, -8, -6],
       [-8, -9, -5, -8]])

In [30]:
arr1>arr2

array([[ True, False, False, False],
       [False, False, False,  True],
       [ True,  True, False, False]])

Numpy - String Operations

In [32]:
#lets create an array of strings
arr=np.array(["Sudh","Kumar"])

In [33]:
arr

array(['Sudh', 'Kumar'], dtype='<U5')

In [34]:
#if we want to convert this into upper case, we use np.char.upper()
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [35]:
#if we want to capitalize the data,we use np.char.capitalize()
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [36]:
#if we want to provide title 
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

Numpy - Mathematical Functions

In [37]:
arr1

array([[6, 2, 1, 5],
       [3, 3, 7, 5],
       [7, 8, 4, 7]])

In [38]:
#using numpy we can perform mathematical functions like finding sin, cos
np.sin(arr1)

array([[-0.2794155 ,  0.90929743,  0.84147098, -0.95892427],
       [ 0.14112001,  0.14112001,  0.6569866 , -0.95892427],
       [ 0.6569866 ,  0.98935825, -0.7568025 ,  0.6569866 ]])

In [39]:
np.cos(arr1)

array([[ 0.96017029, -0.41614684,  0.54030231,  0.28366219],
       [-0.9899925 , -0.9899925 ,  0.75390225,  0.28366219],
       [ 0.75390225, -0.14550003, -0.65364362,  0.75390225]])

In [40]:
np.tan(arr1)

array([[-0.29100619, -2.18503986,  1.55740772, -3.38051501],
       [-0.14254654, -0.14254654,  0.87144798, -3.38051501],
       [ 0.87144798, -6.79971146,  1.15782128,  0.87144798]])

In [41]:
np.log10(arr1)

array([[0.77815125, 0.30103   , 0.        , 0.69897   ],
       [0.47712125, 0.47712125, 0.84509804, 0.69897   ],
       [0.84509804, 0.90308999, 0.60205999, 0.84509804]])

In [42]:
np.exp(arr1)

array([[4.03428793e+02, 7.38905610e+00, 2.71828183e+00, 1.48413159e+02],
       [2.00855369e+01, 2.00855369e+01, 1.09663316e+03, 1.48413159e+02],
       [1.09663316e+03, 2.98095799e+03, 5.45981500e+01, 1.09663316e+03]])

In [44]:
#when use numpy's power function, its important to mention power along with the data that we are passing, in this case 
#we are passing arr1 as our data 2 is power
np.power(arr1,2)

array([[36,  4,  1, 25],
       [ 9,  9, 49, 25],
       [49, 64, 16, 49]])

In [45]:
np.mean(arr1)

4.833333333333333

In [46]:
np.median(arr1)

5.0

In [47]:
np.std(arr1)

2.153807997220014

In [48]:
np.var(arr1)

4.638888888888888

In [49]:
np.min(arr1)

1

In [50]:
np.max(arr1)

8

Numpy - Arithematic Operations

In [51]:
arr1

array([[6, 2, 1, 5],
       [3, 3, 7, 5],
       [7, 8, 4, 7]])

In [52]:
arr2

array([[1, 6, 2, 7],
       [6, 7, 7, 1],
       [3, 7, 7, 7]])

In [54]:
#incase we want to do subtract, there are 2 methods, either we can do arr1-arr2 or use np.subtract
arr1-arr2

array([[ 5, -4, -1, -2],
       [-3, -4,  0,  4],
       [ 4,  1, -3,  0]])

In [55]:
np.subtract(arr1,arr2)

array([[ 5, -4, -1, -2],
       [-3, -4,  0,  4],
       [ 4,  1, -3,  0]])

In [56]:
np.multiply(arr1,arr2)

array([[ 6, 12,  2, 35],
       [18, 21, 49,  5],
       [21, 56, 28, 49]])

In [57]:
#if we want to fetch remainder, we use mod
np.mod(arr1,arr2)

array([[0, 2, 1, 5],
       [3, 3, 0, 0],
       [1, 1, 4, 0]])

In [58]:
np.power(arr1,arr2)

array([[      6,      64,       1,   78125],
       [    729,    2187,  823543,       5],
       [    343, 2097152,   16384,  823543]])

In [59]:
np.sqrt(arr1)

array([[2.44948974, 1.41421356, 1.        , 2.23606798],
       [1.73205081, 1.73205081, 2.64575131, 2.23606798],
       [2.64575131, 2.82842712, 2.        , 2.64575131]])

Numpy - Statistical Functions

In [60]:
np.mean(arr1)

4.833333333333333

In [61]:
np.std(arr1)

2.153807997220014

In [62]:
np.median(arr1)

5.0