## Consider the below code to answer further questions:
### import numpy as np
### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
### array_list = np.array(object = list_)
### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
### to print the data types of both the variables.

In [2]:
import numpy as np

In [8]:
list_1 = [ '1' , '2' , '3' , '4' , '5' ]

In [9]:
array_list = np.array(object = list_1)

In [10]:
type(list_1)

list

In [11]:
type(array_list)

numpy.ndarray

## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [16]:
import numpy as np

list_1 = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_1:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_1 and
### array_list? If so then print the data types of each and every element present in both the variables, list_
### and array_list.

### Answer. Yes, there will be a difference in the data type of the elements present in the variables list_ and array_list dueto the specified dtype=int in the creation of array_list. The elements of array_list will be of integer type.

In [17]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Consider the below code to answer further questions:
### import numpy as np
### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
### num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [18]:
import numpy as np

In [19]:
num_list=[[1,2,3],[4,5,6]]

In [20]:
num_array=np.array(object=num_list)

In [21]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
num_array.shape

(2, 3)

In [24]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [29]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])