In [2]:
import numpy as np

In [3]:
#lets make a list with a range 0 till 5
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
#lets try to produce a list with range 0 to 10 in decimal numbers
list(range(0.4,10.4))
#this is because range deals with only integers

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
#if we want a list of range of decimal numbers we need to use arange(usage:np.arange)
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [7]:
#with arange we can also give step size also
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [8]:
#we can convert the range of number in a list
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [9]:
#if we want to genearte data between 1 to 5 and we want to generate 20 such datas, we use linspace
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
#similarly we can generate logspace, example if we want to generate logspace of 1 to 5 and we want 10 such datas
#by default the base is 10, but if we want diff base we can mention
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [11]:
#if we want to generate zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
#similarly we can generate 0 as matriz with all zeros present
np.zeros((3,4))
#that is 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((3,4,2))
#here we are generating 3 matrices with 4 rows nd 2 columns

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
np.zeros((3,4,4,2))
#here we are generating 3 sets of 4 matrices having 4 rows  2 columns

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [15]:
#similary we can generate 1's
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#lets put the above matrix in arr variable
arr=np.ones((3,4))

In [18]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#if we want to add 5 to each of the matrix elements
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [20]:
#if we want to multiply all the 1's in the matrix with 4
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [21]:
#if we want to generate an empty matrix
np.empty((3,4))
#this will create a small matrix

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [22]:
#if we want to generate identity matrix, we use np.eye
np.eye(5)
#we can notice in a identity matrix, no of rows=no of columns, in this case it has 5 rows and 5 columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr1=np.eye(5)
#lets place this matrix in a dataframe

In [24]:
import pandas as pd

In [25]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [26]:
#another way of generating data in numpy is using randon.rand
np.random.rand(2,3)

array([[0.04301935, 0.24548783, 0.28057662],
       [0.76561235, 0.74980735, 0.1171048 ]])

In [27]:
#similary we have one more way
np.random.randn(2,3)

array([[ 0.87418401,  0.43459565,  0.84834037],
       [-0.01936604,  1.33145219, -0.62237698]])

In [28]:
#the difference between the 2 is randn generates numbers from a normal distribution with a mean of 0 and a standard 
#deviation of 1,while `rand` generates numbers from a uniform distribution between 0 and 1 that is mean, avg or standard deviation 
#could be anything.

In [31]:
#another way of generating randon numbers is using random.randint
np.random.randint(1,5,(3,4))
#here we are asking to generate numbers between 1 to 5 and the shape will be 3 rows 4 columns

array([[4, 3, 1, 1],
       [1, 2, 3, 1],
       [1, 1, 1, 2]])

In [32]:
#lets save the above data in arr2 variable
arr2=np.random.randint(1,5,(3,4))

In [33]:
arr2

array([[4, 2, 3, 3],
       [4, 3, 3, 1],
       [3, 3, 2, 3]])

In [34]:
#if we want to know the number of elements in the matrix
arr2.size

12

In [35]:
#lets find the shape of matrix
arr2.shape

(3, 4)

In [36]:
#now if we want to change the shape or do reshape, also by doing re-shape no of elements will not change(i,e., in this case it is 12)
#before doing reshape we need to make sure that shape should give us a product of the no of elements(should be 12 in this case)
arr2.reshape(6,2)

array([[4, 2],
       [3, 3],
       [4, 3],
       [3, 1],
       [3, 3],
       [2, 3]])

In [37]:
arr2.reshape(2,6)

array([[4, 2, 3, 3, 4, 3],
       [3, 1, 3, 3, 2, 3]])

In [38]:
arr2.reshape(4,3)

array([[4, 2, 3],
       [3, 4, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [39]:
arr2.reshape(1,12)

array([[4, 2, 3, 3, 4, 3, 3, 1, 3, 3, 2, 3]])

In [40]:
#we can also negative numbers also
arr2.reshape(4,-1)

array([[4, 2, 3],
       [3, 4, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [41]:
arr2.reshape(4,-6)

array([[4, 2, 3],
       [3, 4, 3],
       [3, 1, 3],
       [3, 2, 3]])

In [42]:
#we can also do reshape in 3d
arr2.reshape(2,2,3)

array([[[4, 2, 3],
        [3, 4, 3]],

       [[3, 1, 3],
        [3, 2, 3]]])

In [45]:
#lets generate random numbers between 1 to 10 with shape as 5 rows and 6 columns
arr1=np.random.randint(1,10,(5,6))

In [47]:
arr1

array([[9, 7, 8, 4, 7, 1],
       [2, 4, 3, 1, 8, 5],
       [1, 4, 8, 7, 3, 3],
       [6, 5, 8, 1, 4, 7],
       [1, 6, 8, 7, 3, 3]])

In [48]:
#if we want to which all elements in the matrix are greater than 8 for example
arr1>8
#so here in the o/p it will mark true for all elements greater than 8 and false for all elements lesser than 8

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [51]:
#to filter out and give the o/p in terms of numbers, which are greater than 8
arr1[arr1 >8]

array([9])

In [52]:
arr1

array([[9, 7, 8, 4, 7, 1],
       [2, 4, 3, 1, 8, 5],
       [1, 4, 8, 7, 3, 3],
       [6, 5, 8, 1, 4, 7],
       [1, 6, 8, 7, 3, 3]])

In [53]:
#suppose we want to fetch only 9 and 7 present in 0th row and 1 and 2nd columns
arr1[0,[0,1]]

array([9, 7])

In [55]:
#suppose we want to fetch 8,7 in 2 row and 2nd and 3rd column, and want to fetch 8,1 in 3rd row, 2 and 3rd column
#basically we want to fetch data from row 2,3 and column 2,3
arr1[2:4,[2,3]]
#2:4 mean slice and rows 2 and 3 and exclude 4, 2 and 3 are column

array([[8, 7],
       [8, 1]])

In [56]:
#lets generate 2 matrixes usinf=g random.randint and perform addition
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [58]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [2, 1, 2]])

In [59]:
arr2

array([[2, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [60]:
arr1+arr2

array([[3, 2, 3],
       [3, 2, 2],
       [3, 3, 3]])

In [61]:
#lets perform multiplication
arr1*arr2
#note this is index wise multiplication and not matrix multiplication

array([[2, 1, 2],
       [2, 1, 1],
       [2, 2, 2]])

In [62]:
#if we want to do matrix multiplication, we use @ operator
arr1@arr2

array([[6, 6, 4],
       [5, 4, 3],
       [8, 7, 5]])

In [63]:
#if we want to do division operation
arr1/arr2

array([[0.5, 1. , 2. ],
       [0.5, 1. , 1. ],
       [2. , 0.5, 2. ]])

In [64]:
#if we want to divide an matrix by 0 or any number
arr1/0

/tmp/ipykernel_77/2456945294.py:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [65]:
arr1/3

array([[0.33333333, 0.33333333, 0.66666667],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.33333333, 0.66666667]])

Numpy Broadcasting

In [66]:
#lets generate matrix with all 0s
arr1=np.zeros((3,4))

In [67]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
arr1+5
#this is called broadcasting, here we are broadcasting 5 to the matrix

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [70]:
#lets create an array
a=np.array([1,2,3,4,])

In [72]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
arr1+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [74]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
b=np.array([[3,4,5]])

In [79]:
arr+b
#we got this error because shape do ot match, so to fix this error we need to transpose b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [81]:
arr1=arr+b.T

In [82]:
arr1

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [83]:
#if we want to perform square root of all elements in the arr1
np.sqrt(arr1)

array([[2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974]])

In [84]:
#if we want to perform exponent operation
np.exp(arr1)

array([[ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ],
       [403.42879349, 403.42879349, 403.42879349, 403.42879349]])

In [85]:
#we can also find max and min inside the array
np.max(arr1)

6.0

In [86]:
np.min(arr1)

4.0