Numpy - Sort, Search and Counting Functions

In [1]:
import numpy as np

In [2]:
arr=np.array([4,2,8,5,3,9,12,56])

In [3]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [4]:
#searchsorted function in numpy is used this way - np.searchsorted(in this case we have data stored in arr variable, and 
#then we pass the element we want to insert), this way it gives indice where the element needs to be placed so that order
#is maintained
np.searchsorted(arr,6)

5

In [5]:
np.searchsorted(arr,12)

6

In [6]:
np.searchsorted(arr,11)

6

In [7]:
np.searchsorted(arr,43)

7

In [8]:
arr1=np.array([0,324,645,65,6,6,0,0,0,234])

In [9]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [10]:
#to find nonzero elements we use np.count_nonzero, this gives the count of elements that are non zero
np.count_nonzero(arr1)

6

In [11]:
#where function in numpy - we use it this way - np.where(pass the variable where are data is stored, in this case arr1> 1  
#or 2 or any condition)this will return all the indexes where are results are true
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9]),)

In [13]:
np.extract(arr1>2,arr1)
#extarct function will fetch and give all the elements as per the conditions

array([324, 645,  65,   6,   6, 234])

Numpy - Byte Swapping

In [16]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [18]:
arr.byteswap()
#byteswap will show how the above elements are stored in byte, and if you byte info to be displayed everytime you display 
#arr, just type true inside the parenthesis
#arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

Numpy - Copy and Views

In [19]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
a=np.copy(arr1)
#this is deep copy, meaning if we make changes in a, arr1 will not be affected and vice versa

In [21]:
b=arr1.view()
#view means it does shallow copy meaning if we make any changes in b, the changes will be reflected in arr1 also,
#likewise if we do any changes in arr1, those changes will be reflected in b also
#so view is also done the other way, other way of doin it is  - b=arr1

In [22]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [23]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
b[0]=234

In [25]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [26]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

Numpy - Matrix Library

In [27]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)
#this performs same operations that we can on normal matrix, as you can see we can generate zeros using np matrix also
#thes result is same having 2d(1 bracket means 1d, 2 bracket mean 2d)

matrix([[0., 0., 0., 0., 0.]])

In [31]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
#lets create matrix with diagonals
nm.eye(4)
#4 means 4 rows and 4 columns

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Numpy - linear algebra

In [33]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [34]:
arr1=np.random.randint([[2,3],[4,5]])

In [35]:
arr2=np.random.randint([[5,3],[2,5]])

In [36]:
arr1

array([[1, 0],
       [2, 2]])

In [37]:
arr2

array([[3, 1],
       [0, 2]])

In [38]:
np.dot(arr1,arr2)
#The Dot product is a way to multiply two equal-length vectors together.

array([[3, 1],
       [6, 6]])

In [40]:
arr1@arr2

array([[3, 1],
       [6, 6]])