In [1]:
#numpy is mostly used array and matrix calculation
#first we import Numpy
import numpy as np

In [2]:
#lets create a simple list and try to convert it into array
l=[1,2,3,4,5]
#this is our list

In [3]:
#now to convert this into numpy array we np.array()
arr=np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
#lets check the type of arr
type(arr)
#ndarray means n dimensional array

numpy.ndarray

In [6]:
#another way of converting array into array is using asarray, it works the same way as np.arrar
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
#lets try create an array by passing a list inside a list
arr1=np.array([[1,2,3],[2,3,4]])

In [8]:
arr1
#we can notice its a 2 dimensional array

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
#to check dimension of an array, we do it this way using .ndim
arr.ndim

1

In [10]:
arr1.ndim

2

In [11]:
#to make a matrix
mat=np.matrix(l)

In [12]:
mat
#we can notice matrix will have a minimum dimension of 2(op is coming as list under a list, this means its a 2d)

matrix([[1, 2, 3, 4, 5]])

In [13]:
np.asanyarray(l)
#this will convert into an array
#asanyarray,asarray or array are functions that will convert any type of thing into an n dimension array

array([1, 2, 3, 4, 5])

In [14]:
#lets try the same asanyarray with matrix
np.asanyarray(mat)
#we can notice its still a 2d array no change has happened

matrix([[1, 2, 3, 4, 5]])

In [15]:
#lets assign arr to a
a=arr

In [16]:
#lets check value of arr now
arr
#arr is still the same

array([1, 2, 3, 4, 5])

In [17]:
a
#a is also the same as arr

array([1, 2, 3, 4, 5])

In [18]:
#now lets try to change the value at index at 0 in arr and check both a and arr
arr[0]=100

In [19]:
arr

array([100,   2,   3,   4,   5])

In [20]:
a
#this is called shallow copy, here we have just created a and assigned to arr to make another reference
#this is why both have same values
#A shallow copy of an object is a copy whose properties share the same references (point to the same underlying values) 
#as those of the source object from which the copy was made

array([100,   2,   3,   4,   5])

In [21]:
#lets create a variable called and assign arr and do np.copy
b=np.copy(arr)

In [22]:
b

array([100,   2,   3,   4,   5])

In [23]:
#now if we make any changes in arr or b, it will not effect the other, example
b[0]=234

In [24]:
b
#here we can notice b has changed

array([234,   2,   3,   4,   5])

In [25]:
#np.fromfunction is inbuilt numpy function where we can create our own function function to create 
#anything like array, matrix etc
np.fromfunction(lambda i,j:i==j,(3,3))
#here i and j, i are rows and j is columns such that i==j and (3,3) is shape so this way we have 3 x 3 matrix 
# when i and j will be same it will return true and false if not same, that is if i=0 and j=0 it will be true
#when i=1,j=1 true,else false
#when i=2 j=2 true,else false

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
arr
#even when b is changed arr is still the same, it still has 100 in the 0th position
#what has happened is whenever we call np.copy and then assign values, it will create separate memory where it will copy 
#the arr values into the new memory and give reference = b, this way arr dataset is different and b dataset is different
# and any changes made in each other will not effect the other one, meaning any changes made in b dataset will npt effect in 
#arr dataset, and any change made in arr dataset will not effect b dataset. This is called as deep copy.

array([100,   2,   3,   4,   5])

In [27]:
#lets try i*j
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [29]:
iterable=(i*i for i in range(5))

In [30]:
np.fromiter(iterable,dtype=int)

array([ 0,  1,  4,  9, 16])

In [31]:
np.fromstring('23 45 68',sep=' ')
#here 23 45 68 are passed as string, sep is separator, and in here we have specified sep as space

array([23., 45., 68.])

In [32]:
np.fromstring('23,45,68',sep=',')
#here we have specified separator as ,

array([23., 45., 68.])

In [33]:
#so now we know ndim means it will tell how many dimensions are there, 1bracket means 1 dimension, 2 bracket means 
#2dimensions
arr.ndim

1

In [34]:
arr1.ndim

2

In [35]:
#if we want to know how many elements are present in an array, we use np.size
arr.size

5

In [36]:
arr1.size

6

In [37]:
#to know shape of matrix we use .shape
arr.shape
#this means its a 1d array 

(5,)

In [38]:
arr1.shape
#this means it is 2x3 matrix that is 2 rows, 3 columns

(2, 3)

In [39]:
#to check datatype we can use .dtype
arr.dtype

dtype('int64')

In [40]:
arr1.dtype

dtype('int64')